name: brew test-bot
on:
  push:
    branches: master
  pull_request: []
jobs:
  test-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Run brew test-bot
        run: |
          set -e
          brew update
          HOMEBREW_TAP_DIR="/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/rwhogg/homebrew-personal-thirdparty"
          mkdir -p "$HOMEBREW_TAP_DIR"
          rm -rf "$HOMEBREW_TAP_DIR"
          ln -s "$PWD" "$HOMEBREW_TAP_DIR"
          brew test-bot
